// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Amagatsha")>]
[<assembly: AssemblyProductAttribute("Amagatsha")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © TeaDrivenDev 2019")>]
[<assembly: ComVisibleAttribute(false)>]
[<assembly: AssemblyVersionAttribute("1.3.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Amagatsha"
    let [<Literal>] AssemblyProduct = "Amagatsha"
    let [<Literal>] AssemblyCopyright = "Copyright © TeaDrivenDev 2019"
    let [<Literal>] ComVisible = false
    let [<Literal>] AssemblyVersion = "1.3.0"
